# Generated by Django 4.0.3 on 2022-04-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
