# Generated by Django 4.0.3 on 2022-04-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0003_alter_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewthread',
            old_name='posted_at',
            new_name='pub_at',
        ),
    ]
